foreground            #e1e2e7
background            #111417
selection_foreground  #003354
selection_background  #99cbff
url_color             #f5bd61
cursor                #99cbff
cursor_text_color     #003354

color0   #111417
color1   #ffb4ab
color2   #99cbff
color3   #f5bd61
color4   #99cbff
color5   #f5bd61
color6   #b98831
color7   #e1e2e7

color8   #8b919a
color9   #ffb4ab
color10  #99cbff
color11  #f5bd61
color12  #99cbff
color13  #f5bd61
color14  #b98831
color15  #e1e2e7

tab_bar_background              #111417
tab_bar_margin_color            #111417
active_tab_foreground           #003354
active_tab_background           #99cbff
inactive_tab_foreground         #c1c7d0
inactive_tab_background         #111417
